language: python
os: linux
python:
  - "3.8"
# command to install dependencies
script:
  - black --check .
  - flake8 --exclude=migrations .
  - coverage run --source=mysite,polls manage.py test
install:
  - pip install -r requirements.txt