language: python
os: linux
python:
  - "3.8"
script:
  - black --check .
  - flake8 --max-line-length=100 .
  - coverage run --source=mysite,polls manage.py test
install:
  - pip install -r requirements.txt
after_success:
  - python -m coveralls
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "polls-assignment"
  env: "polls-travis-env"
  bucket_name: "elasticbeanstalk-us-east-1-106966609221"
  on:
    branch: master